version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser:v2
    ports:
      - "7777:80"
    volumes:
      - /home/dondoncece/main-storage:/srv
      - ./db/filebrowser.db:/database/filebrowser.db
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
